### ISSUE TITLE
[UI ENHANCEMENT] make the website look better

### ISSUE THREAD

**Issue by anurag596** [NabajitBhadury/Blog-Project#4]
-->going to do some work on html
-->going to add a css file to make website look attractive.

**Comment by NabajitBhadury** [comment]
That's great hope for a good contribution from you @AnuragMalasi

**Comment by NabajitBhadury** [comment]
@AnuragMalasi I have created a Test-UI-Branch push your contribution there

**Comment by anurag596** [comment]
> @AnuragMalasi I have created a Test-UI-Branch push your contribution there

Ok 👍

**Comment by NabajitBhadury** [comment]
@AnuragMalasi I have checked your contribution and I have merged that but after merging I figured out that there is a couple of issue there and thats not suitable so I have reverted that merge
The issue is open and you can make proper changes and commit it there

**Comment by anurag596** [comment]
> @AnuragMalasi I have checked your contribution and I have merged that but after merging I figured out that there is a couple of issue there and thats not suitable so I have reverted that merge The issue is open and you can make proper changes and commit it there

@NabajitBhadury should i push changes to Test-UI-Branch ?

**Comment by NabajitBhadury** [comment]
yes you do this then if your pr is suitable I will merge it

**Comment by NabajitBhadury** [comment]
Sorry buddy someone has solved this issue before you can do this so unfortunately I have to close this one but I hope to have further contribution to other issues of this project
